### PR TITLE
update from field to reply-to if exists, added message-url into messa…

### PR DESCRIPTION
**Pull request by ziweizhou**
sometimes email has a reply to field, which is lost after the normalization. I replaced to field with the value from reply-to. 
also the message-url field is lost as well after the normalization. I included it in the headers. 

please let me know if anything else I need to change.

### CODE REVIEW

**Comment by bradpauly** [comment]
Whoops, I meant to make that comment here.

**Comment by ziweizhou** [comment]
indeed, however i dont see anywhere else to pass these informations except header. 

btw, i also added the file attachment parse logic as well. I believe the current code disgard them 

Regards.

**Comment by strzibny** [comment]
@bradpauly I am now at a point where I need this 'url' param as well. Mailgun docs are confusing but it is included with store() and notify route. Having direct access to what Mailgun sent would be helpful as well.

**Comment by bradpauly** [comment]
@ziweizhou @strzibny sorry this has been open for so long. If you're still interested in passing these along, `vendor_specific` is the best place to do it. See https://github.com/bradpauly/griddler-mailgun/pull/22

**Pull request closed without merging**
